import { useEffect, useState } from 'react'
import { AppShell } from '../components/Shell'
import { adminNav, navigate } from '../components/navigation'
import { Banner, Button, Card, Chip, Field, Stat } from '../components/UI'

function AdminShell({ active, badge = 'Vận hành nền tảng', children }: { active: string; badge?: string; children: React.ReactNode }) {
  return <AppShell kind="admin" badge={badge} status="3 nguồn cần xử lý" nav={adminNav} active={active}>{children}</AppShell>
}

export function AdminHome() {
  return <AdminShell active="/admin"><div className="page-heading"><h1>Tổng quan vận hành</h1><p>Ưu tiên nguồn, phê duyệt và sự cố có ảnh hưởng trực tiếp tới trải nghiệm học.</p></div><Banner tone="warning" title="Có nguồn cần kiểm tra">Ví dụ toán tử mảng thay đổi; cần xem ảnh hưởng.</Banner><div className="three-grid"><Stat value="3" label="nguồn cần xử lý" note="1 nguồn có thay đổi lớn" tone="warning" /><Stat value="2" label="phê duyệt đang chờ" note="bảng thuật ngữ và tiêu chí chấm" /><Stat value="1" label="sự cố nguồn" note="đang dùng bản đã lưu" tone="danger" /></div><div className="dashboard-two"><Card><h3>Nguồn ưu tiên</h3><Card className="warning-outline"><h3 className="text-warning">PostgreSQL 16 · cần quét lại</h3><p>Ví dụ toán tử mảng thay đổi; 4 thuật ngữ và 12 bài học có thể bị ảnh hưởng.</p><Button onClick={() => navigate('/admin/sources')}>Mở quản trị nguồn</Button></Card><div className="source-ok"><span>Python 3.13 · đã xác thực · đồng bộ 8 phút trước</span><Chip tone="success">Ổn định</Chip></div></Card><Card><h3>Ảnh hưởng học tập</h3><div className="metric-list"><p>Bài học liên kết <b className="text-info">12</b></p><p>Kiểm tra khái niệm <b className="text-info">18</b></p><p>Thuật ngữ thay đổi <b className="text-warning">4</b></p><p>Đang dùng bản lưu tạm <b>31</b></p></div></Card></div></AdminShell>
}

export function SourceGovernance({ initial = 'initial' }: { initial?: string }) {
  const [state, setState] = useState(initial)
  useEffect(() => { if (state === 'scanning') { const id = setTimeout(() => setState('impact'), 1200); return () => clearTimeout(id) } }, [state])
  const banners: Record<string, [string, string, 'warning' | 'info' | 'success' | 'danger']> = {
    initial: ['Nguồn cần quét lại', 'PostgreSQL 16 có thay đổi; trình đọc tài liệu vẫn dùng.', 'warning'],
    scanning: ['Đang so sánh phiên bản', 'Đang kiểm tra checksum, headings, ví dụ và thuật ngữ liên kết.', 'info'],
    impact: ['Đã tìm thấy ảnh hưởng', '4 thuật ngữ, 12 bài học và 18 câu kiểm tra cần xem lại.', 'warning'],
    approved: ['Đã phê duyệt phiên bản mới', 'Bản PostgreSQL 16.1 đã pin; lịch sử cũ vẫn giữ 16.0.', 'success'],
    unavailable: ['Nguồn tạm thời không khả dụng', 'Hệ thống tiếp tục phục vụ bản đã lưu và không tự thay nội dung.', 'danger'],
  }
  const [title, message, tone] = banners[state] ?? banners.initial
  return <AdminShell active="/admin/sources" badge="Quản trị nguồn"><div className="page-heading"><h1>Quản lý nguồn tài liệu</h1><p>So sánh thay đổi, xem ảnh hưởng tới bài học, phê duyệt và khôi phục phiên bản trước khi cần.</p></div><Banner tone={tone} title={title}>{message}</Banner><div className="admin-source-layout"><Card><h3>Danh sách nguồn</h3><p>URL, phiên bản và trạng thái phát hành</p>{[['Python docs', '3.13 · đồng bộ 8 phút trước', 'Đã xác thực'], ['MDN JavaScript', '2026.06 · đồng bộ 2 giờ trước', 'Đã xác thực'], ['PostgreSQL', '16.1 · thay đổi ví dụ toán tử mảng', state === 'approved' ? 'Đã xác thực' : 'Cần quét lại'], ['React docs', '19 · đồng bộ hôm nay', 'Đã xác thực']].map(row => <button key={row[0]} className={row[0] === 'PostgreSQL' ? 'selected-source' : ''}><span><b>{row[0]}</b><small>{row[1]}</small></span><Chip tone={row[2] === 'Đã xác thực' ? 'success' : 'warning'}>{row[2]}</Chip></button>)}<div className="source-policy">Trình đọc tài liệu tiếp tục dùng bản đã lưu cho đến khi phê duyệt xong. Không tự động xuất bản thay đổi.</div></Card><Card><span className="eyebrow">{state === 'approved' ? 'ĐÃ PHÊ DUYỆT' : state === 'impact' ? 'ẢNH HƯỞNG' : 'CẦN QUÉT LẠI'}</span><h2>PostgreSQL 16.1</h2><p>Thay đổi phát hiện trong ví dụ toán tử mảng. Quét lại để tính ảnh hưởng tới thuật ngữ và bài học.</p>{state === 'scanning' && <div className="progress"><i /></div>}{state === 'impact' && <Card><p>12 bài học liên kết<br />18 câu kiểm tra khái niệm<br />4 thuật ngữ cần xem lại</p></Card>}<Button onClick={() => setState(state === 'impact' ? 'approved' : 'scanning')} disabled={state === 'scanning'}>{state === 'impact' ? 'Phê duyệt phiên bản' : state === 'scanning' ? 'Đang quét…' : 'Quét lại thay đổi'}</Button><Button tone="secondary" onClick={() => setState('unavailable')}>Mô phỏng nguồn lỗi</Button></Card></div></AdminShell>
}

export function GlossaryPage({ detail = false }: { detail?: boolean }) {
  const [approved, setApproved] = useState(false)
  if (detail) return <AdminShell active="/admin/glossary" badge="Chi tiết thuật ngữ"><div className="page-heading"><h1>microtask</h1><p>So sánh nghĩa, nguồn liên kết và phạm vi ảnh hưởng trước khi phê duyệt.</p></div>{approved && <Banner tone="success" title="Đã phê duyệt thuật ngữ">Phiên bản v1.5 sẽ được dùng cho sáu bài học mới; evidence cũ giữ v1.4.</Banner>}<div className="review-layout"><div><Card><h3>Nghĩa hiện tại</h3><p><b>Tác vụ nhỏ</b> — một đơn vị công việc hẹp, có thể hoàn thành và kiểm chứng độc lập.</p><Chip>MDN 2026.08</Chip></Card><Card><h3>Thay đổi đề xuất</h3><p>Bổ sung ngữ cảnh event loop và loại bỏ ví dụ không còn khớp với MDN.</p><Banner tone="warning" compact title="Ảnh hưởng">6 bài học · 9 câu kiểm tra · 3 ghi chú nguồn</Banner></Card></div><Card><h3>Quyết định</h3><p>Người duyệt phải xác nhận source version, phạm vi và nội dung tiếng Việt.</p><Field label="Ghi chú phê duyệt" value="Đã đối chiếu MDN 2026.08." /><Button onClick={() => setApproved(true)}>Phê duyệt v1.5</Button><Button tone="secondary" onClick={() => navigate('/admin/glossary')}>Quay lại danh sách</Button></Card></div></AdminShell>
  return <AdminShell active="/admin/glossary" badge="Quản trị thuật ngữ"><div className="page-heading"><h1>Thuật ngữ</h1><p>Quản lý nghĩa tiếng Việt, nguồn liên kết và tác động tới bài học.</p></div><Banner tone="warning" title="Một thuật ngữ cần xem lại">microtask thay đổi trong MDN và ảnh hưởng 6 bài học.</Banner><div className="three-grid"><Stat value="128" label="thuật ngữ đã xuất bản" tone="success" /><Stat value="4" label="đang chờ duyệt" tone="warning" /><Stat value="6" label="bài học bị ảnh hưởng" /></div><div className="dashboard-two"><Card><h3>Danh sách thuật ngữ</h3>{[['deque', 'hàng đợi hai đầu · Python 3.13', 'Đã xuất bản'], ['thread-safe', 'an toàn luồng · bảng thuật ngữ v1.4', 'Đã xuất bản'], ['microtask', 'tác vụ vi mô · MDN 2026.08', 'Cần xem lại']].map(row => <button className="glossary-row" key={row[0]} onClick={() => row[0] === 'microtask' && navigate('/admin/glossary/microtask')}><span><b>{row[0]}</b><small>{row[1]}</small></span><Chip tone={row[2] === 'Đã xuất bản' ? 'success' : 'warning'}>{row[2]}</Chip></button>)}</Card><Card><h3>Tác động cần xử lý</h3><p>6 bài học<br />9 kiểm tra khái niệm<br />3 ghi chú nguồn</p><Button onClick={() => navigate('/admin/glossary/microtask')}>Xem thay đổi</Button></Card></div></AdminShell>
}

export function SupportPage({ detail = false }: { detail?: boolean }) {
  const [resolved, setResolved] = useState(false)
  if (detail) return <AdminShell active="/admin/support" badge="Hỗ trợ CM-204"><div className="page-heading"><h1>Nguồn không tải · CM-204</h1><p>Ngữ cảnh được người học cung cấp, không chứa mật khẩu hoặc dữ liệu ẩn.</p></div>{resolved && <Banner tone="success" title="Đã đóng yêu cầu">Người học nhận được hướng dẫn dùng bản nguồn đã lưu.</Banner>}<div className="review-layout"><Card><h3>Bối cảnh người học</h3><p><b>student@codemind.ai</b></p><p>Bước gặp lỗi: Tài liệu → Luyện tập; đang dùng Python 3.13; đã thử tải lại hai lần.</p><h3>Dấu vết hệ thống</h3><p>Source snapshot: available<br />Live fetch: timeout<br />Learning progress: preserved</p></Card><Card><h3>Phản hồi</h3><label className="field"><span>Nội dung</span><textarea defaultValue="Bạn có thể tiếp tục bằng bản Python 3.13 đã lưu. Tiến trình và thuật ngữ đã chọn vẫn được giữ nguyên." /></label><Button onClick={() => setResolved(true)}>Gửi và đóng yêu cầu</Button><Button tone="secondary" onClick={() => navigate('/admin/support')}>Quay lại</Button></Card></div></AdminShell>
  const tickets = [['CM-204', 'Nguồn không tải', 'Cao', 'Đang mở'], ['CM-199', 'Hạn mức AI hiển thị sai', 'Trung bình', 'Đang xử lý'], ['CM-188', 'Không thấy ghi chú', 'Thấp', 'Đã giải quyết']]
  return <AdminShell active="/admin/support" badge="Hỗ trợ người dùng"><div className="page-heading"><h1>Yêu cầu hỗ trợ</h1><p>Ưu tiên sự cố ảnh hưởng tiến trình học và quyền truy cập dữ liệu.</p></div><div className="three-grid"><Stat value="8" label="đang mở" tone="warning" /><Stat value="3" label="ảnh hưởng bài học" tone="danger" /><Stat value="2h 18m" label="thời gian phản hồi" /></div><Card><div className="table-toolbar"><h3>Danh sách yêu cầu</h3><Button tone="secondary">Lọc theo mức độ</Button></div><div className="data-table"><div className="data-table__head"><span>Mã</span><span>Chủ đề</span><span>Mức độ</span><span>Trạng thái</span></div>{tickets.map(row => <button key={row[0]} onClick={() => row[0] === 'CM-204' && navigate('/admin/support/CM-204')}>{row.map(cell => <span key={cell}>{cell}</span>)}</button>)}</div></Card></AdminShell>
}

export function FeedbackPage({ approval = false }: { approval?: boolean }) {
  const [approved, setApproved] = useState(false)
  if (approval) return <AdminShell active="/admin/approval/microtask" badge="Phê duyệt nội dung"><div className="page-heading"><h1>Phê duyệt thay đổi microtask</h1><p>Quyết định dựa trên diff, source version và ảnh hưởng đã mô phỏng.</p></div>{approved && <Banner tone="success" title="Đã phê duyệt">Thay đổi được ghi vào audit log và có thể hoàn tác.</Banner>}<div className="review-layout"><Card><h3>Thay đổi đang chờ</h3><p><b>Thuật ngữ:</b> microtask v1.4 → v1.5</p><p><b>Nguồn:</b> MDN 2026.08</p><p><b>Ảnh hưởng:</b> 6 bài học, 9 câu kiểm tra, 3 ghi chú nguồn.</p><Banner tone="warning" compact title="Không cập nhật ngược">Evidence cũ tiếp tục tham chiếu phiên bản v1.4.</Banner></Card><Card><h3>Xác nhận</h3><label className="consent-inline"><input type="checkbox" defaultChecked /><span><b>Đã xem nguồn và phạm vi</b><small>Không có hidden test hoặc dữ liệu cá nhân trong diff.</small></span></label><Button onClick={() => setApproved(true)}>Phê duyệt thay đổi</Button><Button tone="secondary" onClick={() => navigate('/admin/feedback')}>Hủy</Button></Card></div></AdminShell>
  return <AdminShell active="/admin/feedback" badge="Nội dung & phê duyệt"><div className="page-heading"><h1>Phản hồi nội dung</h1><p>Tập hợp lỗi nguồn, thuật ngữ và tiêu chí chấm trước khi xuất bản.</p></div><div className="three-grid"><Stat value="2" label="đang chờ phê duyệt" tone="warning" /><Stat value="6" label="báo cáo tuần này" /><Stat value="94%" label="giải quyết đúng SLA" tone="success" /></div><Card><h3>Hàng đợi phê duyệt</h3><div className="data-table"><div className="data-table__head"><span>Đối tượng</span><span>Nguồn</span><span>Ảnh hưởng</span><span>Trạng thái</span></div><button onClick={() => navigate('/admin/approval/microtask')}><span>microtask v1.5</span><span>MDN 2026.08</span><span>6 bài học</span><span className="text-warning">Chờ phê duyệt</span></button><button><span>Tiêu chí deque</span><span>Python 3.13</span><span>32 học viên</span><span className="text-info">Đang rà soát</span></button></div></Card></AdminShell>
}

export function SecurityPage({ confirm = false }: { confirm?: boolean }) {
  const [showConfirm, setShowConfirm] = useState(confirm)
  const [revoked, setRevoked] = useState(false)
  return <AdminShell active="/admin/security" badge="Bảo mật"><div className="page-heading"><h1>Bảo mật và phiên thiết bị</h1><p>Quản lý phiên quản trị, audit và thao tác nhạy cảm có xác nhận lại.</p></div><Banner title="Phiên hiện tại được bảo vệ">Mọi truy cập dữ liệu học tập nhạy cảm đều có allow/deny audit event.</Banner><div className="dashboard-two"><Card><h3>Phiên thiết bị</h3>{[['Windows · Codex Desktop', 'Hiện tại · TP.HCM', 'Đang dùng'], ['Chrome · macOS', '2 ngày trước · Hà Nội', revoked ? 'Đã thu hồi' : 'Hoạt động']].map(row => <div className="session-row" key={row[0]}><span><b>{row[0]}</b><small>{row[1]}</small></span><Chip tone={row[2] === 'Đang dùng' ? 'success' : row[2] === 'Đã thu hồi' ? 'muted' : 'warning'}>{row[2]}</Chip>{row[2] === 'Hoạt động' && <Button tone="danger" onClick={() => setShowConfirm(true)}>Thu hồi</Button>}</div>)}</Card><Card><h3>Chính sách quản trị</h3><p>✓ MFA cho thao tác nhạy cảm<br />✓ Audit allow/deny<br />✓ Secret không xuất hiện trong log<br />✓ Session rotation sau đăng nhập</p></Card></div>{showConfirm && <div className="modal-backdrop"><Card className="confirm-modal"><span className="payment-icon danger">!</span><h2>Xác nhận thu hồi phiên</h2><p>Phiên Chrome trên macOS sẽ phải đăng nhập lại. Hành động này được ghi vào audit log.</p><Field label="Nhập THU HỒI để xác nhận" value="THU HỒI" /><Button tone="danger" onClick={() => { setRevoked(true); setShowConfirm(false) }}>Thu hồi phiên</Button><Button tone="secondary" onClick={() => setShowConfirm(false)}>Hủy</Button></Card></div>}</AdminShell>
}
