import { useEffect, useState } from 'react'
import { AppShell } from '../components/Shell'
import { navigate, studentNav } from '../components/navigation'
import { Banner, Button, Card, Chip, CodeBlock, EmptyState, Stat } from '../components/UI'

const before = `item = queue[0]\nqueue = queue[1:]\nreturn item`
const after = `if not queue:\n    return None\nreturn queue.popleft()`

function StudentShell({ active, step, children }: { active: string; step: number; children: React.ReactNode }) {
  return <AppShell kind="student" badge={active === '/student' ? 'Bài học: deque' : active.includes('docs') ? 'Tài liệu chính thức' : active.includes('notes') ? 'Ghi chú học tập' : 'Luyện tập: deque'} status={`Bước ${step} / 5`} nav={studentNav} active={active}>{children}</AppShell>
}

export function StudentHome() {
  return <StudentShell active="/student" step={2}><div className="page-heading"><h1>Hôm nay</h1><p>Bắt đầu từ bài cần học tiếp, lỗi gần nhất và lịch ôn hôm nay.</p></div><div className="student-home-grid"><Card className="featured-card"><span className="eyebrow">BÀI HỌC TIẾP THEO</span><h2>Hiểu deque từ một lỗi biên cụ thể</h2><p>Đọc tài liệu Python 3.13, chọn thuật ngữ “thread-safe”, chạy kiểm thử và tự sửa mã sau gợi ý từng bước.</p><p>3–4 phút &nbsp;&nbsp; 0 / 5 bước</p><div className="action-row"><Button onClick={() => navigate('/student/docs')}>Tiếp tục bài học</Button><Button tone="secondary" onClick={() => navigate('/student/notes')}>Xem ghi chú</Button></div></Card><Card><h3>Kết quả gần nhất</h3><p>Giảng viên chỉ xem khi bạn đã bật quyền hiển thị.</p><strong className="metric-inline text-warning">4 / 5</strong><small>kiểm thử đạt</small><strong className="metric-inline">2</strong><small>gợi ý đã dùng</small><strong className="metric-inline text-success">1</strong><small>ghi chú đã lưu</small></Card><Card><h3>Ôn lại hôm nay</h3><p>Thuật ngữ “thread-safe” và lỗi điều kiện biên sẽ đến hạn sau bài học.</p></Card><Card><h3>Cam kết học tập</h3><p>AI chỉ gợi ý từng bước. Mã nộp và phần giải thích vẫn là của bạn.</p><Chip tone="success">Đang áp dụng</Chip></Card></div></StudentShell>
}

export function StudentDocs({ selected = false }: { selected?: boolean }) {
  const [term, setTerm] = useState(selected)
  return <StudentShell active="/student/docs" step={1}><div className="page-heading"><h1>Đọc nguồn trước khi sửa mã</h1><p>Nguồn, phiên bản và thuật ngữ được lưu cùng bài học để bạn dễ xem lại.</p></div><Banner tone="success" title="Nguồn đã xác thực">Python 3.13 · URL và phiên bản được lưu cùng bài học.</Banner><div className="content-sidebar-grid"><Card><h2>collections.deque</h2><p>Deque là hàng đợi hai đầu hỗ trợ append và pop với độ phức tạp gần O(1) ở cả hai phía.</p><CodeBlock>{`“Deques support thread-safe, memory-efficient appends and pops from either side.”`}</CodeBlock><button className={`term-button ${term ? 'selected' : ''}`} onClick={() => setTerm(!term)}>thread-safe</button><p>Hãy chọn một thuật ngữ, giải thích theo cách của bạn rồi liên hệ với ca kiểm thử.</p></Card><div><Card><span className="eyebrow">BƯỚC 1 / 5</span><h3>Chọn “thread-safe”</h3><p>Không dịch máy ngay. Chọn thuật ngữ để xem nghĩa, nguồn và quan hệ với ca kiểm thử.</p><Button onClick={() => setTerm(true)}>Chọn “thread-safe”</Button></Card><Card><span className="eyebrow">NGUỒN CHÍNH THỨC</span><h3>Python 3.13 · collections.deque</h3><code>docs.python.org/3/library/collections.html</code></Card></div></div>{term && <Banner title="Thuật ngữ đã lưu">“thread-safe” được gắn với source version Python 3.13.</Banner>}<div className="page-actions"><Button disabled={!term} onClick={() => navigate('/student/concept')}>Tiếp tục kiểm tra khái niệm</Button></div></StudentShell>
}

export function StudentConcept({ state = 'initial' }: { state?: string }) {
  const [answer, setAnswer] = useState(state === 'wrong' ? 'size' : state === 'correct' ? 'ops' : '')
  const checked = Boolean(answer)
  const correct = answer === 'ops'
  return <StudentShell active="/student/concept" step={2}><div className="page-heading"><h1>Kiểm tra khái niệm</h1><p>Chọn quan hệ đúng từ nguồn vừa đọc trước khi chuyển sang mã.</p></div>{checked && <Banner tone={correct ? 'success' : 'danger'} title={correct ? 'Đúng — deque hỗ trợ thao tác hai đầu' : 'Chưa đúng — hãy nhìn lại đối tượng của O(1)'}>{correct ? 'Bạn đã nối deque → append/pop → O(1).' : 'maxlen giới hạn số phần tử, không phải nguyên nhân làm append/pop gần O(1).'}</Banner>}<Card className="quiz-card"><span className="eyebrow">CÂU 1 / 1</span><h2>Phát biểu nào mô tả đúng nhất quan hệ giữa deque và O(1)?</h2><div className="answer-list"><button className={answer === 'ops' ? 'selected' : ''} onClick={() => setAnswer('ops')}><b>Append và pop ở hai đầu có độ phức tạp gần O(1)</b><small>Áp dụng cho thao tác ở hai phía của deque.</small></button><button className={answer === 'size' ? 'selected' : ''} onClick={() => setAnswer('size')}><b>O(1) nghĩa là deque luôn chỉ có một phần tử</b><small>Nhầm giữa độ phức tạp và kích thước.</small></button><button className={answer === 'thread' ? 'selected' : ''} onClick={() => setAnswer('thread')}><b>Thread-safe đồng nghĩa mọi chương trình đều chạy song song</b><small>Không đúng phạm vi của thuật ngữ.</small></button></div><div className="action-row"><Button tone="secondary" onClick={() => navigate('/student/docs')}>Xem lại nguồn</Button><Button disabled={!correct} onClick={() => navigate('/student/practice')}>Bắt đầu luyện tập</Button></div></Card></StudentShell>
}

export function StudentPractice({ initial = 'idle' }: { initial?: string }) {
  const [state, setState] = useState(initial)
  useEffect(() => { if (state === 'loading') { const id = setTimeout(() => setState('fail'), 900); return () => clearTimeout(id) } }, [state])
  const result = state === 'pass' ? ['5 / 5 đạt', 'success'] : state === 'fail' || state === 'hint' ? ['4 / 5 đạt', 'warning'] : ['Chưa chạy', 'muted']
  return <StudentShell active="/student/practice" step={3}><div className="page-heading"><h1>Luyện tập với mã</h1><p>Đề bài, trình soạn mã, bộ kiểm thử và trợ giảng AI nằm trên cùng một màn hình.</p></div><Banner title={state === 'loading' ? 'Đang chạy kiểm thử' : state === 'pass' ? 'Tự sửa thành công' : 'Sẵn sàng chạy'}>{state === 'pass' ? 'Năm ca kiểm thử đạt; mã trước/sau đã được ghi lại.' : 'Năm ca kiểm thử: kết quả, hàng đợi rỗng và thay đổi trạng thái.'}</Banner><div className="practice-layout student-practice"><Card><span className="eyebrow">ĐỀ BÀI</span><h3>Lấy phần tử đầu và cập nhật chính deque</h3><p>Viết hàm consume(queue) trả về phần tử đầu; nếu rỗng, trả về None.</p><p>✓ queue rỗng → None<br />✓ trả về phần tử đầu<br />✓ cập nhật deque ban đầu<br />✓ không tạo đáp án từ AI</p><CodeBlock>{`Nguồn\nPython 3.13 · collections.deque`}</CodeBlock></Card><Card className="editor-card"><div className="tabs"><button className="active">Mã</button><button>Kiểm thử</button><button>Trợ giảng AI</button></div><CodeBlock>{state === 'pass' ? after : before}</CodeBlock><p>Mã bạn đang viết sẽ không bị mất khi có lỗi.</p><Button disabled={state === 'loading'} onClick={() => setState('loading')}>{state === 'loading' ? 'Đang chạy…' : 'Chạy 5 kiểm thử'}</Button></Card><Card><span className="eyebrow">KIỂM THỬ</span><h3 className={`text-${result[1]}`}>{result[0]}</h3>{state === 'loading' ? <div className="progress"><i /></div> : state === 'idle' ? <p>5 ca đang chờ. Không có dữ liệu được ghi trước khi bạn bấm chạy.</p> : state === 'pass' ? <><p>✓ Hàng đợi rỗng</p><p>✓ Trả về phần tử đầu</p><p>✓ Cập nhật chính deque</p><Button onClick={() => navigate('/student/review')}>Xem bằng chứng</Button></> : <><p>✓ 4 ca đã đạt</p><p className="text-danger">× Hàm tạo list mới thay vì cập nhật deque gốc.</p><Button onClick={() => setState('hint')}>Mở gợi ý</Button>{state === 'hint' && <Banner title="Gợi ý tầng 1">Phép cắt queue[1:] tạo đối tượng mới. Phương thức nào thay đổi chính deque?</Banner>}<Button onClick={() => setState('pass')}>Tự sửa và chạy lại</Button></>}</Card></div></StudentShell>
}

export function StudentReview() {
  return <StudentShell active="/student/review" step={4}><div className="page-heading"><h1>Xem lại lần tự sửa</h1><p>Mã trước/sau, ca kiểm thử và gợi ý được đặt cạnh nhau để giải thích tiến bộ.</p></div><Banner tone="success" title="Đạt sau khi tự sửa">5 / 5 kiểm thử · 2 gợi ý · nguồn Python 3.13.</Banner><div className="before-after"><Card className="danger-outline"><span className="text-danger">TRƯỚC</span><CodeBlock>{before}</CodeBlock><p>Queue gốc không thay đổi.</p></Card><Card className="success-outline"><span className="text-success">SAU</span><CodeBlock>{after}</CodeBlock><p>Dùng popleft() để cập nhật chính deque.</p></Card></div><div className="three-grid"><Stat value="4 → 5/5" label="Kiểm thử" tone="success" /><Stat value="2" label="Gợi ý đã dùng" tone="warning" /><Stat value="1" label="Quyết định sửa" tone="info" /></div><div className="page-actions"><Button onClick={() => navigate('/student/notes')}>Lưu thành ghi chú</Button></div></StudentShell>
}

export function StudentNotes({ empty = false }: { empty?: boolean }) {
  const [isEmpty, setEmpty] = useState(empty)
  if (isEmpty) return <StudentShell active="/student/notes" step={5}><EmptyState title="Chưa có ghi chú học tập" action={<Button onClick={() => setEmpty(false)}>Tạo từ lần tự sửa gần nhất</Button>}>Khi hoàn thành một lần tự sửa, bạn có thể lưu lỗi, nguồn và quyết định sửa thành lịch ôn.</EmptyState></StudentShell>
  return <StudentShell active="/student/notes" step={5}><div className="page-heading"><h1>Ghi chú học tập</h1><p>Lỗi, thuật ngữ và quyết định sửa mã được giữ lại để ôn đúng thời điểm.</p></div><Banner tone="success" title="Đã lưu ghi chú">Ghi chú từ bài deque đã được thêm vào lịch ôn ngày mai.</Banner><div className="content-sidebar-grid"><Card><span className="eyebrow">THAY ĐỔI TRẠNG THÁI · DEQUE</span><h2>Cập nhật chính đối tượng, không thay biến cục bộ</h2><p>Khi cần giữ thay đổi bên ngoài hàm, gán queue = queue[1:] chỉ đổi biến cục bộ. Với deque, popleft() vừa trả về phần tử đầu vừa cập nhật chính đối tượng.</p><div className="before-after compact"><CodeBlock>{before}</CodeBlock><CodeBlock tone="success">{after}</CodeBlock></div><CodeBlock>{`Nguồn: Python 3.13 · collections.deque\nTạo từ: ca lỗi thay đổi trạng thái · 1 gợi ý · 5/5 kiểm thử`}</CodeBlock></Card><Card><h3>Lịch ôn</h3><h2 className="text-info">Ngày mai · 09:00</h2><p>Câu hỏi ôn: phương thức nào vừa lấy phần tử trái vừa cập nhật deque?</p><Chip>deque</Chip> <Chip>thay đổi trạng thái</Chip><Button onClick={() => navigate('/student')}>Về Hôm nay</Button><Button tone="secondary" onClick={() => setEmpty(true)}>Xem trạng thái trống</Button></Card></div></StudentShell>
}
