import { useState } from 'react'
import { AppShell } from '../components/Shell'
import { navigate, teacherNav } from '../components/navigation'
import { Banner, Button, Card, Chip, CodeBlock, Stat } from '../components/UI'

function TeacherShell({ active, children }: { active: string; children: React.ReactNode }) {
  return <AppShell kind="teacher" badge={active === '/teacher/builder' ? 'CS101 · Trình soạn bài' : 'CS101 · Lập trình cơ bản'} status="Chỉ hiển thị dữ liệu người học đã đồng ý chia sẻ" nav={teacherNav} active={active}>{children}</AppShell>
}

export function TeacherHome() {
  return <TeacherShell active="/teacher"><div className="page-heading"><h1>Việc cần xử lý hôm nay</h1><p>Ưu tiên bài cần phản hồi, nguồn cần xem và học viên cần can thiệp.</p></div><Banner title="Chỉ hiển thị dữ liệu đã được chia sẻ">Chỉ hiển thị dữ liệu người học đã đồng ý chia sẻ.</Banner><div className="three-grid"><Stat value="12" label="bài chờ chấm" note="4 bài có ca kiểm thử lỗi" tone="warning" /><Stat value="3" label="nguồn cần xem" note="2 thay đổi bảng thuật ngữ" /><Stat value="8" label="học viên cần can thiệp" note="dựa trên lỗi lặp lại" tone="danger" /></div><div className="dashboard-two"><Card><h3>Bài ưu tiên</h3><Card className="highlight-row"><div><h3>Minh Anh · bài deque</h3><p>5 / 5 kiểm thử · 1 gợi ý · mã trước/sau đã lưu</p><small className="text-success">Người học đã đồng ý chia sẻ quá trình làm bài.</small></div><Button onClick={() => navigate('/teacher/review')}>Xem bài làm</Button></Card><div className="list-row"><span>Hoàng Nam · recursion · 3 / 5 kiểm thử</span><Chip tone="warning">Cần phản hồi</Chip></div></Card><Card><h3>Tình trạng lớp</h3><div className="metric-list"><p>Đã hoàn tất hôm nay <b className="text-success">18 / 32</b></p><p>Còn lỗi thay đổi trạng thái <b className="text-warning">7</b></p><p>Chưa cho phép xem quá trình <b>4</b></p><p>Nguồn đang chờ duyệt <b className="text-info">3</b></p></div></Card></div></TeacherShell>
}

export function ClassesPage() {
  return <TeacherShell active="/teacher/classes"><div className="page-heading"><h1>Lớp học</h1><p>Chọn lớp theo việc cần ưu tiên hôm nay, thay vì dựa vào nhãn phong cách học.</p></div><Banner title="Chỉ hiển thị dữ liệu đã được chia sẻ">Chỉ tổng hợp dữ liệu người học đã đồng ý chia sẻ.</Banner><div className="three-grid"><Stat value="32" label="học viên" note="18 đã hoàn tất hôm nay" tone="success" /><Stat value="7" label="lỗi lặp lại" note="chủ yếu là thay đổi trạng thái" tone="warning" /><Stat value="4" label="chưa chia sẻ" note="không hiển thị chi tiết" tone="info" /></div><div className="dashboard-two"><Card><h3>Lớp đang hoạt động</h3><Card className="highlight-row"><div><h3>CS101 · Cấu trúc dữ liệu</h3><p>32 học viên · bài deque đang mở</p><b className="text-warning">7 học viên cần phản hồi</b></div><Button onClick={() => navigate('/teacher/roster')}>Mở lớp</Button></Card><div className="list-row"><b>CS201 · Thuật toán</b><span className="text-warning">2 nguồn đang chờ phê duyệt</span></div></Card><Card><h3>Việc cần làm</h3><p>1. Phản hồi bài Minh Anh<br />2. Kiểm tra nguồn PostgreSQL<br />3. Giao bài queue tiếp theo</p><Button tone="secondary" onClick={() => navigate('/teacher/assignments')}>Mở bài tập</Button></Card></div></TeacherShell>
}

export function RosterPage() {
  const students = [
    ['Minh Anh', 'Đã chia sẻ', '5 / 5', '1 gợi ý'],
    ['Hoàng Nam', 'Đã chia sẻ', '3 / 5', 'Cần phản hồi'],
    ['Lan Chi', 'Không chia sẻ', '—', 'Ẩn chi tiết'],
    ['Bảo Trân', 'Đã chia sẻ', '4 / 5', '2 gợi ý'],
  ]
  return <TeacherShell active="/teacher/roster"><div className="page-heading"><h1>CS101 · Học viên</h1><p>Quản lý danh sách lớp và quyền hiển thị theo từng phiên học.</p></div><Banner title="Consent quyết định mức chi tiết">Học viên không chia sẻ chỉ xuất hiện ở mức membership, không có mã hay lịch sử gợi ý.</Banner><Card><div className="table-toolbar"><h3>Danh sách học viên</h3><Button tone="secondary">Mời học viên</Button></div><div className="data-table"><div className="data-table__head"><span>Học viên</span><span>Quyền hiển thị</span><span>Kết quả</span><span>Trạng thái</span></div>{students.map((row) => <button key={row[0]} onClick={() => row[1] === 'Đã chia sẻ' && navigate('/teacher/review')}>{row.map((cell, i) => <span key={cell} className={i === 1 ? row[1] === 'Đã chia sẻ' ? 'text-success' : 'text-muted' : ''}>{cell}</span>)}</button>)}</div></Card></TeacherShell>
}

export function AssignmentsPage() {
  return <TeacherShell active="/teacher/assignments"><div className="page-heading page-heading--actions"><div><h1>Bài tập</h1><p>Tạo bài từ nguồn đã xác thực và tiêu chí phản hồi có thể kiểm chứng.</p></div><Button onClick={() => navigate('/teacher/builder')}>Tạo bài tập</Button></div><div className="three-grid"><Stat value="3" label="đang mở" tone="info" /><Stat value="12" label="bài chờ chấm" tone="warning" /><Stat value="2" label="nguồn cần duyệt" tone="danger" /></div><Card><h3>Danh sách bài tập</h3><div className="data-table"><div className="data-table__head"><span>Bài tập</span><span>Nguồn</span><span>Tiến độ</span><span>Trạng thái</span></div>{[['Deque và thay đổi trạng thái', 'Python 3.13', '18 / 32', 'Đang mở'], ['Độ phức tạp O(1)', 'Python 3.13', '24 / 32', 'Đang chấm'], ['Recursion cơ bản', 'MDN', '—', 'Bản nháp']].map(row => <button key={row[0]} onClick={() => navigate('/teacher/review')}>{row.map(cell => <span key={cell}>{cell}</span>)}</button>)}</div></Card></TeacherShell>
}

export function AssignmentBuilder({ ready = false }: { ready?: boolean }) {
  const [isReady, setReady] = useState(ready)
  return <TeacherShell active="/teacher/builder"><div className="page-heading"><h1>Tạo bài tập</h1><p>Soạn từ nguồn đã xác thực, ca kiểm thử và tiêu chí phản hồi có thể kiểm chứng.</p></div>{isReady ? <Banner tone="success" title="Sẵn sàng xuất bản">Nguồn, ba thuật ngữ, năm ca kiểm thử và tiêu chí phản hồi đã hợp lệ.</Banner> : <Banner title="Nguồn đã xác thực">Python 3.13 · collections.deque · đồng bộ 8 phút trước.</Banner>}<div className="builder-layout"><div><Card><h3>Nguồn chính thức</h3><p>Python 3.13 · collections.deque</p><small>URL, phiên bản và trạng thái xác thực sẽ đi cùng bài nộp.</small></Card><div className="two-grid"><Card><h3>Thuật ngữ</h3><p>thread-safe<br />thay đổi trạng thái<br />popleft()</p></Card><Card><h3>Ca kiểm thử</h3><p>✓ hàng đợi rỗng<br />✓ trả về phần tử đầu<br />✓ cập nhật deque gốc<br />✓ giữ thứ tự<br />✓ xử lý một phần tử</p></Card></div><Card><h3>Tiêu chí phản hồi</h3><p>Kết quả đúng · giải thích có căn cứ · tự sửa sau gợi ý · không sao chép đáp án.</p></Card></div><div><Card><h3>Kiểm tra trước khi lưu</h3><p>32 học viên<br />1 nguồn đã xác thực<br />3 thuật ngữ<br />5 ca kiểm thử<br />1 tiêu chí chấm phản hồi</p><Button onClick={() => setReady(true)}>{isReady ? 'Xuất bản bài tập' : 'Lưu và xem trước'}</Button></Card><Card><h3>Quyền hiển thị</h3><p>Giảng viên chỉ thấy nguồn, kiểm thử, gợi ý và mã khi người học bật quyền cho bài tập đó.</p></Card></div></div></TeacherShell>
}

export function AssignmentReview({ saved = false }: { saved?: boolean }) {
  const [feedback, setFeedback] = useState(saved ? 'Bạn đã xác định đúng nguyên nhân: phép cắt tạo list mới. Hãy bổ sung một câu giải thích vì sao popleft() giữ thay đổi trên deque gốc.' : '')
  const [isSaved, setSaved] = useState(saved)
  return <TeacherShell active="/teacher/review"><div className="page-heading"><h1>Chấm bài · Minh Anh</h1><p>Phản hồi dựa trên nguồn, ca kiểm thử, mã trước/sau và gợi ý người học đã dùng.</p></div>{isSaved && <Banner tone="success" title="Đã lưu phản hồi">Phản hồi chỉ hiển thị cho Minh Anh và có audit timestamp.</Banner>}<div className="review-layout"><div><Card><div className="table-toolbar"><div><h3>Deque và thay đổi trạng thái</h3><p>Python 3.13 · 5/5 kiểm thử · 1 gợi ý</p></div><Chip tone="success">Đã chia sẻ</Chip></div><div className="before-after compact"><div><span className="text-danger">TRƯỚC</span><CodeBlock>{`item = queue[0]\nqueue = queue[1:]`}</CodeBlock></div><div><span className="text-success">SAU</span><CodeBlock>{`if not queue: return None\nreturn queue.popleft()`}</CodeBlock></div></div></Card><Card><h3>Dấu vết học tập</h3><p>09:12 · đọc Python 3.13<br />09:16 · 4/5 kiểm thử<br />09:18 · mở gợi ý tầng 1<br />09:21 · tự sửa đạt 5/5</p></Card></div><Card><h3>Phản hồi</h3><label className="field"><span>Nội dung phản hồi</span><textarea value={feedback} onChange={(e) => setFeedback(e.target.value)} placeholder="Gắn phản hồi với bằng chứng cụ thể…" /></label><div className="rating-row"><button>Đúng kết quả</button><button>Có căn cứ</button><button>Tự sửa</button></div><Button disabled={!feedback.trim()} onClick={() => setSaved(true)}>Lưu phản hồi</Button><Button tone="secondary" onClick={() => navigate('/teacher')}>Về danh sách</Button></Card></div></TeacherShell>
}
