from typing import Protocol

from .models import (
    AIInteraction,
    AnalyticsEvent,
    ConsentPurpose,
    LearningEvidence,
    LearningSession,
    Lesson,
    Submission,
    User,
    UserConsent,
)


class Repository(Protocol):
    def get_user(self, user_id: str) -> User | None: ...

    def find_user_by_email(self, email: str) -> User | None: ...

    def get_lesson(self, slug: str) -> Lesson | None: ...

    def get_session(self, session_id: str) -> LearningSession | None: ...

    def save_session(self, session: LearningSession) -> None: ...

    def list_sessions(self) -> list[LearningSession]: ...

    def get_user_consent(self, user_id: str, purpose: ConsentPurpose) -> UserConsent | None: ...

    def save_user_consent(self, consent: UserConsent) -> None: ...

    def get_submission(self, submission_id: str) -> Submission | None: ...

    def save_submission(self, submission: Submission) -> None: ...

    def find_submission_by_key(self, session_id: str, idempotency_key: str) -> Submission | None: ...

    def get_interaction(self, interaction_id: str) -> AIInteraction | None: ...

    def save_interaction(self, interaction: AIInteraction) -> None: ...

    def list_interactions(self, session_id: str) -> list[AIInteraction]: ...

    def get_evidence(self, session_id: str) -> LearningEvidence | None: ...

    def save_evidence(self, evidence: LearningEvidence) -> None: ...

    def save_analytics_event(self, event: AnalyticsEvent) -> None: ...

    def list_analytics_events(
        self,
        session_id: str | None = None,
        user_id: str | None = None,
        event_name: str | None = None,
    ) -> list[AnalyticsEvent]: ...

    def create_deletion_request(self, user_id: str) -> str: ...
