export type DesignViewport = 'desktop' | 'mobile'

export type DesignSpec = {
  id: string
  name: string
  group: 'public' | 'lesson' | 'student' | 'teacher' | 'admin'
  path: string
  viewport: DesignViewport
}

const d = (
  id: string,
  name: string,
  group: DesignSpec['group'],
  path: string,
  viewport: DesignViewport = name.includes('Mobile') ? 'mobile' : 'desktop',
): DesignSpec => ({ id, name, group, path, viewport })

export const designs: DesignSpec[] = [
  // Public, authentication, policies, commerce and the six-step lesson flow.
  d('10402:4820', 'Home • Desktop', 'public', '/'),
  d('10402:5014', 'Home • Mobile', 'public', '/'),
  d('10402:5139', 'Login • Desktop / Default', 'public', '/login'),
  d('10402:5166', 'Login • Mobile / Default', 'public', '/login'),
  d('10534:146', 'Login • Desktop / Error', 'public', '/login?state=error'),
  d('10534:147', 'Login • Mobile / Error', 'public', '/login?state=error'),
  d('10402:5186', 'Register • Desktop / Consent required', 'public', '/register?state=consent'),
  d('10402:5217', 'Register • Mobile / Consent required', 'public', '/register?state=consent'),
  d('10534:148', 'Register • Desktop / Ready', 'public', '/register?state=ready'),
  d('10534:149', 'Register • Mobile / Ready', 'public', '/register?state=ready'),
  d('10402:5241', 'Pricing • Desktop', 'public', '/pricing'),
  d('10402:5289', 'Pricing • Mobile', 'public', '/pricing'),
  d('10402:5454', 'For Campus • Desktop', 'public', '/campus'),
  d('10402:5520', 'For Campus • Mobile', 'public', '/campus'),
  d('10402:5552', 'Help Center • Desktop', 'public', '/help'),
  d('10402:5597', 'Help Center • Mobile', 'public', '/help'),
  d('10542:216', 'Help Article • Source Reliability • Desktop', 'public', '/help/source-reliability'),
  d('10542:217', 'Help Article • Source Reliability • Mobile', 'public', '/help/source-reliability'),
  d('10542:218', 'Help Source Unavailable • Desktop', 'public', '/help/source-reliability?state=offline'),
  d('10542:219', 'Help Source Unavailable • Mobile', 'public', '/help/source-reliability?state=offline'),
  d('10402:5630', 'About CodeMind AI • Desktop', 'public', '/about'),
  d('10402:5668', 'About CodeMind AI • Mobile', 'public', '/about'),
  d('10402:5688', 'Contact • Desktop', 'public', '/contact'),
  d('10402:5730', 'Contact • Mobile', 'public', '/contact'),
  d('10554:248', 'Contact • Desktop / Submitted', 'public', '/contact?state=submitted'),
  d('10554:249', 'Contact • Mobile / Submitted', 'public', '/contact?state=submitted'),
  d('10402:5759', 'Checkout • Desktop', 'public', '/checkout'),
  d('10402:5799', 'Checkout • Mobile', 'public', '/checkout'),
  d('10402:5822', 'Payment Success • Desktop', 'public', '/payment/success'),
  d('10402:5847', 'Payment Success • Mobile', 'public', '/payment/success'),
  d('10402:5863', 'Payment Failed • Desktop', 'public', '/payment/failed'),
  d('10402:5888', 'Payment Failed • Mobile', 'public', '/payment/failed'),
  d('10402:5904', 'Privacy • Desktop', 'public', '/privacy'),
  d('10402:5949', 'Privacy • Mobile', 'public', '/privacy'),
  d('10402:5987', 'Terms • Desktop', 'public', '/terms'),
  d('10402:6032', 'Terms • Mobile', 'public', '/terms'),
  d('10402:6070', 'AI Learning Policy • Desktop', 'public', '/ai-policy'),
  d('10402:6115', 'AI Learning Policy • Mobile', 'public', '/ai-policy'),
  d('10402:6153', 'Academic Integrity • Desktop', 'public', '/integrity'),
  d('10402:6198', 'Academic Integrity • Mobile', 'public', '/integrity'),

  d('10496:2', 'Product Demo • Desktop / 00A • Chưa cam kết', 'lesson', '/demo/setup?state=required'),
  d('10500:79', 'Product Demo • Mobile / 00A • Chưa cam kết', 'lesson', '/demo/setup?state=required'),
  d('10496:46', 'Product Demo • Desktop / 00B • Đã cam kết', 'lesson', '/demo/setup?state=committed'),
  d('10500:110', 'Product Demo • Mobile / 00B • Đã cam kết', 'lesson', '/demo/setup?state=committed'),
  d('10496:90', 'Product Demo • Desktop / 00C • Giảng viên có thể xem', 'lesson', '/demo/setup?state=visible'),
  d('10500:142', 'Product Demo • Mobile / 00C • Giảng viên có thể xem', 'lesson', '/demo/setup?state=visible'),
  d('10402:5312', 'Product Demo • Desktop / 01 • Mục tiêu', 'lesson', '/demo/objective'),
  d('10402:5409', 'Product Demo • Mobile / 01 • Mục tiêu', 'lesson', '/demo/objective'),
  d('10448:79', 'Product Demo • Desktop / 02A • Tài liệu', 'lesson', '/demo/source'),
  d('10448:109', 'Product Demo • Desktop / 02B • Đã chọn thuật ngữ', 'lesson', '/demo/source?state=selected'),
  d('10466:2', 'Product Demo • Mobile / 02 • Tài liệu', 'lesson', '/demo/source'),
  d('10448:141', 'Product Demo • Desktop / 03A • Kiểm tra khái niệm', 'lesson', '/demo/concept'),
  d('10448:173', 'Product Demo • Desktop / 03B • Khái niệm đã nối', 'lesson', '/demo/concept?state=linked'),
  d('10466:3', 'Product Demo • Mobile / 03 • Luyện tập', 'lesson', '/demo/concept'),
  d('10448:205', 'Product Demo • Desktop / 04A • Sẵn sàng chạy', 'lesson', '/demo/practice?state=ready'),
  d('10448:237', 'Product Demo • Desktop / 04B • Đang chạy kiểm thử', 'lesson', '/demo/practice?state=loading'),
  d('10453:79', 'Product Demo • Desktop / 04C • 4 trên 5 đạt', 'lesson', '/demo/practice?state=fail'),
  d('10466:4', 'Product Demo • Mobile / 04 • Lỗi và gợi ý', 'lesson', '/demo/practice?state=fail'),
  d('10453:80', 'Product Demo • Desktop / 05A • Câu hỏi Socratic', 'lesson', '/demo/ai?state=question'),
  d('10453:81', 'Product Demo • Desktop / 05B • Từ chối đáp án và gợi ý', 'lesson', '/demo/ai?state=hint1'),
  d('10453:82', 'Product Demo • Desktop / 05C • Gợi ý tầng 2', 'lesson', '/demo/ai?state=hint2'),
  d('10453:83', 'Product Demo • Desktop / 05D • Gợi ý tầng 3', 'lesson', '/demo/ai?state=hint3'),
  d('10456:36', 'Product Demo • Desktop / 05E • Tự sửa và đạt 5 trên 5', 'lesson', '/demo/ai?state=pass'),
  d('10457:36', 'Product Demo • Desktop / 05B • Phản hồi câu trả lời sai', 'lesson', '/demo/ai?state=wrong'),
  d('10466:5', 'Product Demo • Mobile / 05 • Bằng chứng', 'lesson', '/demo/ai?state=pass'),
  d('10456:37', 'Product Demo • Desktop / 06 • Bằng chứng tiến bộ', 'lesson', '/demo/evidence'),
  d('10502:85', 'Product Demo • Desktop / P1 • Source unavailable', 'lesson', '/demo/error?state=source'),
  d('10502:118', 'Product Demo • Desktop / P1 • Quota exceeded', 'lesson', '/demo/error?state=quota'),
  d('10502:151', 'Product Demo • Desktop / P1 • Submission error', 'lesson', '/demo/error?state=submission'),
  d('10502:184', 'Product Demo • Desktop / P1 • Notes empty', 'lesson', '/demo/error?state=notes'),

  // Student application.
  d('10402:2018', 'Student Home • Desktop', 'student', '/student'),
  d('10402:2117', 'Student Home • Mobile', 'student', '/student'),
  d('10402:2529', 'Official Docs Reader • Desktop', 'student', '/student/docs'),
  d('10402:2601', 'Official Docs Reader • Mobile', 'student', '/student/docs'),
  d('10518:313', 'Official Docs Reader • Desktop / Term selected', 'student', '/student/docs?state=selected'),
  d('10518:314', 'Official Docs Reader • Mobile / Term selected', 'student', '/student/docs?state=selected'),
  d('10402:3180', 'Concept Check • Desktop / initial', 'student', '/student/concept'),
  d('10402:3234', 'Concept Check • Mobile / initial', 'student', '/student/concept'),
  d('10520:341', 'Concept Check • Desktop / wrong', 'student', '/student/concept?state=wrong'),
  d('10520:342', 'Concept Check • Mobile / wrong', 'student', '/student/concept?state=wrong'),
  d('10520:343', 'Concept Check • Desktop / correct', 'student', '/student/concept?state=correct'),
  d('10520:344', 'Concept Check • Mobile / correct', 'student', '/student/concept?state=correct'),
  d('10402:3047', 'Coding Practice • Desktop / idle', 'student', '/student/practice'),
  d('10402:3150', 'Coding Practice • Mobile / idle', 'student', '/student/practice'),
  d('10521:363', 'Coding Practice • Desktop / loading', 'student', '/student/practice?state=loading'),
  d('10521:364', 'Coding Practice • Mobile / loading', 'student', '/student/practice?state=loading'),
  d('10521:365', 'Coding Practice • Desktop / fail', 'student', '/student/practice?state=fail'),
  d('10521:366', 'Coding Practice • Mobile / fail', 'student', '/student/practice?state=fail'),
  d('10521:367', 'Coding Practice • Desktop / hint', 'student', '/student/practice?state=hint'),
  d('10521:368', 'Coding Practice • Mobile / hint', 'student', '/student/practice?state=hint'),
  d('10521:369', 'Coding Practice • Desktop / pass', 'student', '/student/practice?state=pass'),
  d('10521:370', 'Coding Practice • Mobile / pass', 'student', '/student/practice?state=pass'),
  d('10402:3252', 'Practice Review • Desktop', 'student', '/student/review'),
  d('10402:3326', 'Practice Review • Mobile', 'student', '/student/review'),
  d('10402:4344', 'Learning Notes • Desktop / Saved', 'student', '/student/notes'),
  d('10402:4420', 'Learning Notes • Mobile / Saved', 'student', '/student/notes'),
  d('10522:467', 'Learning Notes • Desktop / Empty', 'student', '/student/notes?state=empty'),
  d('10522:468', 'Learning Notes • Mobile / Empty', 'student', '/student/notes?state=empty'),

  // Teacher / Campus application.
  d('10402:6464', 'Teacher Home • Desktop', 'teacher', '/teacher'),
  d('10402:6555', 'Teacher Home • Mobile', 'teacher', '/teacher'),
  d('10402:6594', 'Classes • Desktop', 'teacher', '/teacher/classes'),
  d('10402:6658', 'Classes • Mobile', 'teacher', '/teacher/classes'),
  d('10402:6689', 'Class & Roster Management • Desktop', 'teacher', '/teacher/roster'),
  d('10402:6784', 'Class & Roster Management • Mobile', 'teacher', '/teacher/roster'),
  d('10402:6810', 'Assignments • Desktop', 'teacher', '/teacher/assignments'),
  d('10402:6888', 'Assignments • Mobile', 'teacher', '/teacher/assignments'),
  d('10402:6923', 'Assignment Builder • Desktop', 'teacher', '/teacher/builder'),
  d('10402:7001', 'Assignment Builder • Mobile', 'teacher', '/teacher/builder'),
  d('10547:623', 'Assignment Builder • Desktop / Ready', 'teacher', '/teacher/builder?state=ready'),
  d('10547:624', 'Assignment Builder • Mobile / Ready', 'teacher', '/teacher/builder?state=ready'),
  d('10402:7028', 'Teacher Assignment Review • Desktop / Draft', 'teacher', '/teacher/review'),
  d('10402:7093', 'Teacher Assignment Review • Mobile / Draft', 'teacher', '/teacher/review'),
  d('10526:239', 'Teacher Assignment Review • Desktop / Saved', 'teacher', '/teacher/review?state=saved'),
  d('10526:240', 'Teacher Assignment Review • Mobile / Saved', 'teacher', '/teacher/review?state=saved'),

  // Admin application.
  d('10402:8343', 'Admin Home • Desktop', 'admin', '/admin'),
  d('10402:8408', 'Admin Home • Mobile', 'admin', '/admin'),
  d('10402:8632', 'Admin Source Governance • Desktop / initial', 'admin', '/admin/sources'),
  d('10402:8698', 'Admin Source Governance • Mobile / initial', 'admin', '/admin/sources'),
  d('10528:206', 'Admin Source Governance • Desktop / scanning', 'admin', '/admin/sources?state=scanning'),
  d('10528:207', 'Admin Source Governance • Mobile / scanning', 'admin', '/admin/sources?state=scanning'),
  d('10528:208', 'Admin Source Governance • Desktop / impact', 'admin', '/admin/sources?state=impact'),
  d('10528:209', 'Admin Source Governance • Mobile / impact', 'admin', '/admin/sources?state=impact'),
  d('10528:210', 'Admin Source Governance • Desktop / approved', 'admin', '/admin/sources?state=approved'),
  d('10528:211', 'Admin Source Governance • Mobile / approved', 'admin', '/admin/sources?state=approved'),
  d('10528:212', 'Admin Source Governance • Desktop / unavailable', 'admin', '/admin/sources?state=unavailable'),
  d('10528:213', 'Admin Source Governance • Mobile / unavailable', 'admin', '/admin/sources?state=unavailable'),
  d('10402:8726', 'Glossary Management • Desktop', 'admin', '/admin/glossary'),
  d('10402:8782', 'Glossary Management • Mobile', 'admin', '/admin/glossary'),
  d('10549:374', 'Glossary Detail • Desktop', 'admin', '/admin/glossary/microtask'),
  d('10549:375', 'Glossary Detail • Mobile', 'admin', '/admin/glossary/microtask'),
  d('10402:9075', 'Support Tickets • Desktop', 'admin', '/admin/support'),
  d('10402:9129', 'Support Tickets • Mobile', 'admin', '/admin/support'),
  d('10549:376', 'Support Ticket Detail • Desktop', 'admin', '/admin/support/CM-204'),
  d('10549:377', 'Support Ticket Detail • Mobile', 'admin', '/admin/support/CM-204'),
  d('10402:9163', 'Content Feedback & Reports • Desktop', 'admin', '/admin/feedback'),
  d('10402:9245', 'Content Feedback & Reports • Mobile', 'admin', '/admin/feedback'),
  d('10549:378', 'Approval Detail • Desktop', 'admin', '/admin/approval/microtask'),
  d('10549:379', 'Approval Detail • Mobile', 'admin', '/admin/approval/microtask'),
  d('10402:9419', 'Security & Device Sessions • Desktop', 'admin', '/admin/security'),
  d('10402:9477', 'Security & Device Sessions • Mobile', 'admin', '/admin/security'),
  d('10549:380', 'Security Confirm • Desktop', 'admin', '/admin/security?state=confirm'),
  d('10549:381', 'Security Confirm • Mobile', 'admin', '/admin/security?state=confirm'),
]

export const designsById = new Map(designs.map((item) => [item.id.replace(':', '-'), item]))

export const groupLabels: Record<DesignSpec['group'], string> = {
  public: 'Public & Auth',
  lesson: 'Lesson Demo',
  student: 'Student App',
  teacher: 'Teacher Campus',
  admin: 'Admin Console',
}
